trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

jobs:
  - job: SyncToGitHub
    displayName: "Sync Azure DevOps Repo to GitHub"
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - script: |
          echo " - - - - - - - - - - - - - - - - - - - - - - - - -"
          echo "Reflecting Azure DevOps repo changes to GitHub repo"
          echo " - - - - - - - - - - - - - - - - - - - - - - - - -"

          # Define directories
          stageDir=$(Build.SourcesDirectory)
          githubDir="$stageDir/gitHub"
          destination="$githubDir/AzureDevopsRepoPOC"

          # Define URLs and credentials
          sourceURL="https://$(AzureDevOpsPAT)@dev.azure.com/milindpatil/AzureDevopsRepoPOC/_git/AzureDevopsRepoPOC"
          destURL="https://patil-milind:$(GitPAT)@github.com/patil-milind/AzureDevopsRepoPOC.git"

          # Check if parent directory exists and delete it if needed
          if [ -d "$githubDir" ]; then
            echo "Removing existing $githubDir directory..."
            rm -rf "$githubDir"
          fi

          # Create a new directory and clone the Azure DevOps repo
          echo "Creating directory $githubDir..."
          mkdir -p "$githubDir"
          cd "$githubDir"
          
          echo "Cloning Azure DevOps repository..."
          git clone --mirror "$sourceURL" "$destination"

          cd "$destination"

          # Configure GitHub as a remote and push changes
          echo "Configuring GitHub as remote..."
          git remote rm secondary || true
          git remote add secondary "$destURL"

          # Fetch and push all branches and tags
          echo "Fetching from Azure DevOps repo..."
          git fetch --all
          echo "Pushing all branches and tags to GitHub..."
          git push secondary --mirror

          # Clean up the GitHub directory
          cd "$stageDir"
          if [ -d "$githubDir" ]; then
            echo "Cleaning up $githubDir directory..."
            rm -rf "$githubDir"
          fi

          echo "Azure DevOps repo synced with GitHub repo successfully."
        displayName: "Sync changes to GitHub"
        env:
          GITHUB_TOKEN: $(GitPAT)
          AZURE_DEVOPS_PAT: $(AzureDevOpsPAT)
