trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

jobs:
  - job: SyncToGitHub
    displayName: "Sync Azure DevOps Repo to GitHub"
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - script: |
          echo "Setting up Git configuration..."
          git config --global user.name "patil-milind"
          git config --global user.email "milind.patl02@gmail.com"

          echo "Adding GitHub remote..."
          git remote add github "https://$(GITHUB_TOKEN)@github.com/patil-milind/AzureDevopsRepoPOC.git"
          git fetch github

          echo "Pushing changes to GitHub..."
          git push github --all --force
          git push github --tags --force
        displayName: "Sync changes to GitHub"
        env:
          GITHUB_TOKEN: $(GitDestinationPAT) # Use your GitHub PAT from Azure DevOps secrets
