trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

jobs:
  - job: SyncToGitHub
    displayName: "Sync Azure DevOps Repo to GitHub"
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - script: |
          echo "Setting up Git configuration..."
          git config --global user.name "patil-milind"
          git config --global user.email "milind.patl02@gmail.com"

          echo "Checking for existing GitHub remote..."
          if git remote | grep -q github; then
            echo "Removing existing GitHub remote..."
            git remote remove github
          fi

          echo "Adding GitHub remote..."
          git remote add github "https://$GITHUB_TOKEN@github.com/patil-milind/AzureDevopsRepoPOC.git"
          
          echo "Fetching from GitHub to ensure connection..."
          git fetch github

          echo "Pushing all branches and tags to GitHub..."
          git push --mirror github
        displayName: "Sync changes to GitHub"
        env:
          GITHUB_TOKEN: $(GitPAT)
